export default {
  ProfileSetup: 'ProfileSetup',
  Login: 'SignInScreen',
  Register: 'SignUpScreen',
  CreatePet: 'CreatePet',
  ProfileTab: 'ProfileTab',
  SinglePost: 'SinglePost',
  CreateCaption: 'CreateCaption',
  PetScreenResults: 'PetScreenResults',
  PetProfileViewScreen: 'PetProfileViewScreen',
  HomeTabScreen: 'HomeTabScreen',
  UserProfile: 'UserProfile',
  CreatePost: 'CreatePost',
  EditProfile: 'EditProfile',
  EditPetProfile: 'EditPetProfile',
  LoginScreen: 'LoginScreen',
  ForgotPassword: 'ForgotPassword',
  SelectPetToView: 'SelectPetToViewFromList',
  BlockedAccounts: 'BlockedAccountsList',
};
